Add files via upload

diff --git a/holesurf b/holesurf
--- a/holesurf
+++ b/holesurf
@@ -44,9 +44,9 @@ _READ()
     local c1 c2 c3
     local IFS
 
-    while IFS='&' read -r c1 c2 c3 c4 c5; do
+    while IFS='&' read -r c1 c2 c4 c5 c6; do
         [[ "$c1" =~ ^# ]] && continue
-        echo -e "HOLE:\t$c1\nIP:\t$c2\nCOMM:\t$c5\n--------------------------------------------\n"
+        echo -e "HOLE:\t${c1}\nIP:\t${c2}\nPORT:\t${c5}\nCOM:\t${c6}\n--------------------------------------------\n"
     done <"$HOLELIST"
     return 0
 }
@@ -73,8 +73,7 @@ _SECURE_PASS()
 [[ "$UID" = '0' ]] && { echo "Root? Is not secure. ABORT"; exit 1 ;} # Root?
 [[ ! -d "$USERDIR" ]] && mkdir -v "$USERDIR" # create a underhole directory
 if [[ ! -e "$HOLELIST" ]]; then # Exist hole-list?
-    echo '# | HOLE | | IP | | PASS | SALT | COMMENT |#' > "$HOLELIST"
-    echo 'dadhole&192.168.0.2&921955344cf0b42c9a289f37feeee7e5778ca452e6d327703091f926e5b08c19&FF9vr&The Dad of Holes.' >> "$HOLELIST"
+    echo 'dadhole&192.168.0.2&thedadhole&12000&The 1s Hole Wiki.' >> "$HOLELIST"
 fi
 
 ##############################################
@@ -83,29 +82,43 @@ fi
 
 case $1 in
     sync) # Sync hole-list
-        shift # down
-        OLDIFS="$IFS"
-        inc='0'
-        # Print
-        while IFS='&' read -r column1 column2 column3 column4 column5; do
-            [[ "$column1" =~ ^# ]] && continue
-            inc=$(($inc + 1))
-            echo -e "($inc) $column1 - $column2 - $column5"
-        done < "$HOLELIST"
-        read -p $'\nServer to Sync: ' select_server
-        # Only numbers.
-        ! [[ "$select_server" =~ ^[0-9]+$ ]] && { echo "$select_server Invalid Option."; exit 1 ;}
+          shift # down
+          OLDIFS="$IFS" # Save IFS.
+          inc='0' # Increment var
+          # Print
+          while IFS='&' read -r column1 column2 column3 column4; do
+              [[ "$column1" =~ ^# ]] && continue
+              echo -e "${red}[ $inc ]${end} $column1-$column2"
+              options[i++]="$column1&$column2&$column3&$column4" # Capture all line
+              inc=$(($inc + 1)) # Inc for Menu
+          done < "$HOLELIST"
+          read -p $'\n\033[37;44;1mServer to Sync:\033[m ' select_server
+          if ! [[ "$select_server" =~ ^[0-9]+$ ]]; then
+              echo "$select_server Invalid Option."
+              exit 1
+          fi
+          # Capture Fields and Sync
+          HOLE="$(cut -d '&' -f 1 <<< ${options[$select_server]})"
+          HOST="$(cut -d '&' -f 2 <<< ${options[$select_server]})"
+          PASS="$(cut -d '&' -f 3 <<< ${options[$select_server]})"
+          PORT="$(cut -d '&' -f 4 <<< ${options[$select_server]})"
+          # Convert Hash + Salt
+          
+          # Password arg Rsync
+          RSYNC_PASSWORD="$PASS"
+          echo -e "${blue}Syncing${end} ${USERNAME} ${blue}ON${end} ${HOST} ..."
+          if rsync -avzh rsync://${HOLE}@${HOST}:${PORT}/hole/ "${USERDIR}/${HOLE}"; then
+              echo -e "${yellow}========Sync OK${end}"
+              echo -e "${blue}========Available in:${end} ${USERDIR}/${HOLE}"
+              $BROWSER "${USERDIR}/${HOLE}"
+          else
+              echo -e "${red}========SYNC ERROR. ${HOLE}${HOST}${end}"
+          fi
     ;;
 
     show)
-        shift # Down.
-        [[ -e "$HOLELIST" ]] && _READ
-    ;;
-
-    add)
-        shift
-        read -p "Password of Hole: " password
-        _SECURE_PASS "$password"
+          shift # Down.
+          [[ -e "$HOLELIST" ]] && _READ
     ;;
 esac
 
